import React, { useState, useRef } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import {
  Upload, Loader2, AlertTriangle, CheckCircle2, FileText,
  Sparkles, X, Plus, Package
} from "lucide-react";
import { toast } from "sonner";
import moment from "moment";

// Generate a simple text cert as a Blob
function generateCertBlob(technicianName, skillName, issuedDate) {
  const content = `SKILL CERTIFICATION\n${"=".repeat(40)}\n\nCertified: ${technicianName}\nSkill: ${skillName}\nIssued: ${issuedDate}\nStatus: System Generated\n\n${"=".repeat(40)}\nThis certificate was auto-generated by the system.`;
  return new Blob([content], { type: "text/plain" });
}

export default function BulkSkillImport({ open, onClose, onDone, technicianId, technicianName }) {
  const fileRefs = useRef({});
  const [selected, setSelected] = useState({}); // skillId -> { skill_name, issued_date, expiry_date, cert_file_url, cert_file_name, uploading, genning }
  const [submitting, setSubmitting] = useState(false);

  const { data: skills = [] } = useQuery({
    queryKey: ["skills"],
    queryFn: () => base44.entities.Skill.list("name", 500),
  });

  const { data: existingCerts = [] } = useQuery({
    queryKey: ["skillCerts", technicianId],
    queryFn: () => base44.entities.MemberSkillCert.filter({ technician_id: technicianId }),
    enabled: !!technicianId,
  });

  const existingSkillIds = new Set(existingCerts.map(c => c.skill_id));
  const availableSkills = skills.filter(s => !existingSkillIds.has(s.id));

  const toggleSkill = (skill) => {
    setSelected(prev => {
      if (prev[skill.id]) {
        const next = { ...prev };
        delete next[skill.id];
        return next;
      }
      return { ...prev, [skill.id]: { skill_name: skill.name, issued_date: moment().format("YYYY-MM-DD"), expiry_date: "", cert_file_url: "", cert_file_name: "", uploading: false, genning: false } };
    });
  };

  const updateField = (skillId, field, value) => {
    setSelected(prev => ({ ...prev, [skillId]: { ...prev[skillId], [field]: value } }));
  };

  const handleFileUpload = async (skillId, file) => {
    if (!file) return;
    updateField(skillId, "uploading", true);
    const { file_url } = await base44.integrations.Core.UploadFile({ file });
    setSelected(prev => ({ ...prev, [skillId]: { ...prev[skillId], cert_file_url: file_url, cert_file_name: file.name, uploading: false } }));
  };

  const handleGenCert = async (skillId) => {
    const entry = selected[skillId];
    if (!entry) return;
    updateField(skillId, "genning", true);
    const blob = generateCertBlob(technicianName, entry.skill_name, entry.issued_date);
    const fileName = `cert_${technicianName.replace(/\s+/g, "_")}_${entry.skill_name.replace(/\s+/g, "_")}.txt`;
    const file = new File([blob], fileName, { type: "text/plain" });
    const { file_url } = await base44.integrations.Core.UploadFile({ file });
    setSelected(prev => ({ ...prev, [skillId]: { ...prev[skillId], cert_file_url: file_url, cert_file_name: fileName, genning: false } }));
    toast.success(`Auto-cert generated for ${entry.skill_name}`);
  };

  const handleSubmit = async () => {
    const entries = Object.entries(selected);
    if (entries.length === 0) return;
    setSubmitting(true);
    for (const [skillId, data] of entries) {
      await base44.entities.MemberSkillCert.create({
        technician_id: technicianId,
        technician_name: technicianName,
        skill_id: skillId,
        skill_name: data.skill_name,
        issued_date: data.issued_date,
        expiry_date: data.expiry_date || undefined,
        cert_file_url: data.cert_file_url || undefined,
        cert_file_name: data.cert_file_name || undefined,
        status: "pending",
        reviewer_note: !data.cert_file_url ? "⚠️ Cert file not uploaded — please attach later" : undefined,
      });
    }
    setSubmitting(false);
    toast.success(`${entries.length} skill(s) submitted for review`);
    setSelected({});
    onDone?.();
    onClose();
  };

  const selectedCount = Object.keys(selected).length;
  const missingCert = Object.values(selected).filter(s => !s.cert_file_url).length;

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Package className="w-4 h-4 text-blue-500" />
            Bulk Skill Import — {technicianName}
          </DialogTitle>
        </DialogHeader>

        {/* Skills checklist */}
        <div className="space-y-2">
          <Label className="text-xs text-slate-500 uppercase tracking-wide">Select Skills to Add</Label>
          {availableSkills.length === 0 ? (
            <p className="text-sm text-slate-400 text-center py-4">All skills already added</p>
          ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {availableSkills.map(skill => {
                const isSelected = !!selected[skill.id];
                return (
                  <button
                    key={skill.id}
                    onClick={() => toggleSkill(skill)}
                    className={`text-left px-3 py-2 rounded-lg border text-sm transition-all ${
                      isSelected
                        ? "border-blue-400 bg-blue-50 text-blue-700 font-medium"
                        : "border-slate-200 bg-white text-slate-600 hover:border-slate-300"
                    }`}
                  >
                    <div className="flex items-center gap-2">
                      <div className={`w-3.5 h-3.5 rounded border-2 flex items-center justify-center shrink-0 ${isSelected ? "border-blue-500 bg-blue-500" : "border-slate-300"}`}>
                        {isSelected && <CheckCircle2 className="w-2.5 h-2.5 text-white" />}
                      </div>
                      <span className="truncate">{skill.name}</span>
                    </div>
                    {skill.category && <p className="text-[10px] text-slate-400 mt-0.5 ml-5">{skill.category}</p>}
                  </button>
                );
              })}
            </div>
          )}
        </div>

        {/* Selected skill details */}
        {selectedCount > 0 && (
          <div className="space-y-3 border-t pt-4">
            <div className="flex items-center justify-between">
              <Label className="text-xs text-slate-500 uppercase tracking-wide">{selectedCount} Skill(s) Selected</Label>
              {missingCert > 0 && (
                <div className="flex items-center gap-1.5 text-xs text-amber-600 bg-amber-50 border border-amber-200 rounded-lg px-2 py-1">
                  <AlertTriangle className="w-3.5 h-3.5" />
                  {missingCert} skill(s) missing cert — will be flagged for upload later
                </div>
              )}
            </div>

            {Object.entries(selected).map(([skillId, data]) => (
              <div key={skillId} className="border border-slate-200 rounded-xl p-3 space-y-3 bg-slate-50/50">
                <div className="flex items-center justify-between">
                  <p className="text-sm font-semibold text-slate-800">{data.skill_name}</p>
                  <button onClick={() => toggleSkill({ id: skillId, name: data.skill_name })} className="text-slate-400 hover:text-red-500">
                    <X className="w-4 h-4" />
                  </button>
                </div>

                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <Label className="text-xs">Issued Date</Label>
                    <Input type="date" value={data.issued_date} onChange={e => updateField(skillId, "issued_date", e.target.value)} className="h-8 text-sm" />
                  </div>
                  <div>
                    <Label className="text-xs">Expiry Date (optional)</Label>
                    <Input type="date" value={data.expiry_date} onChange={e => updateField(skillId, "expiry_date", e.target.value)} className="h-8 text-sm" />
                  </div>
                </div>

                {/* Cert file */}
                {data.cert_file_url ? (
                  <div className="flex items-center gap-2 p-2 bg-emerald-50 border border-emerald-200 rounded-lg">
                    <FileText className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                    <span className="text-xs text-emerald-700 truncate flex-1">{data.cert_file_name}</span>
                    <button onClick={() => setSelected(prev => ({ ...prev, [skillId]: { ...prev[skillId], cert_file_url: "", cert_file_name: "" } }))} className="text-slate-400 hover:text-red-500">
                      <X className="w-3 h-3" />
                    </button>
                  </div>
                ) : (
                  <div className="space-y-1.5">
                    <div className="flex items-center gap-1.5 text-xs text-amber-600">
                      <AlertTriangle className="w-3.5 h-3.5" />
                      No cert file — upload now or flag for later
                    </div>
                    <div className="flex gap-2">
                      <input
                        ref={el => fileRefs.current[skillId] = el}
                        type="file"
                        className="hidden"
                        accept=".pdf,.jpg,.jpeg,.png"
                        onChange={e => handleFileUpload(skillId, e.target.files?.[0])}
                      />
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-7 text-xs gap-1 flex-1"
                        disabled={data.uploading}
                        onClick={() => fileRefs.current[skillId]?.click()}
                      >
                        {data.uploading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Upload className="w-3 h-3" />}
                        Upload Cert
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-7 text-xs gap-1 flex-1 text-purple-600 border-purple-200 hover:bg-purple-50"
                        disabled={data.genning}
                        onClick={() => handleGenCert(skillId)}
                      >
                        {data.genning ? <Loader2 className="w-3 h-3 animate-spin" /> : <Sparkles className="w-3 h-3" />}
                        Auto GenCert
                      </Button>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={onClose}>Cancel</Button>
          <Button
            onClick={handleSubmit}
            disabled={submitting || selectedCount === 0}
            className="gap-1.5"
          >
            {submitting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
            Submit {selectedCount > 0 ? `${selectedCount} Skill(s)` : ""}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}